src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;


/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(
 *     fields={"email"},
 *     message= "email already exists log in instead"
 * )
 * @method string getUserIdentifier()
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Email()
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $FirstName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min="6", minMessage="Password should at least be 6 chars")
     */
    private $password;
    /**
     * @Assert\EqualTo(propertyPath="password", message="Confirmation not equal to password")
     */

    public $confirm_password;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $username;
    /**
     * @ORM\Column(type="string", length=100)
     */
    private $LastName;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Image;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $Matricule;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $Nationalite;

    /**
     * @ORM\Column(type="string", length=2)
     */
    private $Sexe;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $Tel;

    /**
     * @ORM\Column(type="json", nullable=true)
     */
    private $Roles = [];

    /**
     * @ORM\OneToMany(targetEntity=Tache::class, mappedBy="user")
     */
    private $taches;

    /**
     * @ORM\OneToMany(targetEntity=UserProjet::class, mappedBy="user")
     */
    private $userProjets;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $dateEmbauche;

    public function __construct()
    {
        $this->taches = new ArrayCollection();
        $this->userProjets = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }


    public function getEmail(): ?string
    {
        return $this->email;
    }


    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->FirstName;
    }


    public function setFirstName(string $FirstName): self
    {
        $this->FirstName = $FirstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->LastName;
    }


    public function setLastName(string $LastName): self
    {
        $this->LastName = $LastName;

        return $this;
    }

   

    public function getImage()
    {
        return $this->Image;
    }

    public function setImage($Image): self
    {
        $this->Image = $Image;

        return $this;
    }

    public function getMatricule(): ?string
    {
        return $this->Matricule;
    }


    public function setMatricule(?string $Matricule): self
    {
        $this->Matricule = $Matricule;

        return $this;
    }

    public function getNationalite(): ?string
    {
        return $this->Nationalite;
    }


    public function setNationalite(?string $Nationalite): self
    {
        $this->Nationalite = $Nationalite;

        return $this;
    }

    public function getSexe(): ?string
    {
        return $this->Sexe;
    }

    public function setSexe(string $Sexe): self
    {
        $this->Sexe = $Sexe;

        return $this;
    }

    public function getTel(): ?string
    {
        return $this->Tel;
    }


    public function setTel(?string $Tel): self
    {
        $this->Tel = $Tel;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }


    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getConfirmPassword(): ?string
    {
        return $this->confirm_password;
    }


    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }
    public function getSalt()
    {
        // TODO: Implement getSalt() method.
    }
    public function getRoles():array
    {
        $roles = $this->Roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(?array $Roles): self
    {
        $this->Roles = $Roles;

        return $this;
    }

    /**
     * @return Collection<int, Tache>
     */
    public function getTaches(): Collection
    {
        return $this->taches;
    }

    public function addTach(Tache $tach): self
    {
        if (!$this->taches->contains($tach)) {
            $this->taches[] = $tach;
            $tach->setUser($this);
        }

        return $this;
    }

    public function removeTach(Tache $tach): self
    {
        if ($this->taches->removeElement($tach)) {
            // set the owning side to null (unless already changed)
            if ($tach->getUser() === $this) {
                $tach->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, UserProjet>
     */
    public function getUserProjets(): Collection
    {
        return $this->userProjets;
    }

    public function addUserProjet(UserProjet $userProjet): self
    {
        if (!$this->userProjets->contains($userProjet)) {
            $this->userProjets[] = $userProjet;
            $userProjet->setUser($this);
        }

        return $this;
    }

    public function removeUserProjet(UserProjet $userProjet): self
    {
        if ($this->userProjets->removeElement($userProjet)) {
            // set the owning side to null (unless already changed)
            if ($userProjet->getUser() === $this) {
                $userProjet->setUser(null);
            }
        }

        return $this;
    }

    public function __toString() {
        return $this->username;
    }

    public function getDateEmbauche(): ?\DateTimeInterface
    {
        return $this->dateEmbauche;
    }

    public function setDateEmbauche(?\DateTimeInterface $dateEmbauche): self
    {
        $this->dateEmbauche = $dateEmbauche;

        return $this;
    }


}

src/Form/ProjetType.php
<?php

namespace App\Form;

use App\Entity\Projet;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProjetType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('intitule')
            // ->add('dateDebut')
            // ->add('dateFin')
            ->add('budget')
            // ->add('etat')
            ->add('description' , TextareaType::class)
            ->add('Categorie')
            ->add('client')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Projet::class,
        ]);
    }
}

src/Controller/ProjetController.php
<?php

namespace App\Controller;

use App\Entity\Phase;
use App\Entity\Projet;
use App\Form\ProjetType;
use App\Repository\PhaseRepository;
use App\Repository\ProjetRepository;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

/**
 * @Route("/projet")
 */
class ProjetController extends AbstractController
{
    /**
     * @Route("/", name="app_projet_index", methods={"GET"})
     */
    public function index(ProjetRepository $projetRepository): Response
    {
        // AELH : redirect to login if tried to access via route
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        return $this->render('projet/index.html.twig', [
            'projets' => $projetRepository->findAll(),
        ]);
    }

    /**
     * @IsGranted("ROLE_OWNER")
     * @Route("/new", name="app_projet_new", methods={"GET", "POST"})
     */
    public function new(Request $request, ProjetRepository $projetRepository): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        $projet = new Projet();
        $form = $this->createForm(ProjetType::class, $projet);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $projet->setEtat('Open');
            
            $projetRepository->add($projet, true);

            return $this->redirectToRoute('app_projet_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('projet/new.html.twig', [
            'projet' => $projet,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_projet_show", methods={"GET"})
     */
    public function show(Projet $projet , ManagerRegistry $em , $id, PhaseRepository $phaseRepository): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        $repo = $em->getRepository(Projet::class);
        $projet = $repo->find($id);

        $userProjets = $projet->getUserProjets()->getValues();
        // dd($userProjets);

        //AELH check repo
        $phases = $phaseRepository->ShowProjectPhase($id);


        return $this->render('projet/show.html.twig', [
            'projet' => $projet,
            'employees' => $userProjets,
            'phases' => $phases
        ]);
    }

    /**
     * @IsGranted("ROLE_OWNER")
     * @Route("/{id}/edit", name="app_projet_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Projet $projet, ProjetRepository $projetRepository): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        $form = $this->createForm(ProjetType::class, $projet);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $projetRepository->add($projet, true);

            return $this->redirectToRoute('app_projet_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('projet/edit.html.twig', [
            'projet' => $projet,
            'form' => $form,
        ]);
    }

    /**
     * @IsGranted("ROLE_OWNER")
     * @Route("/{id}", name="app_projet_delete", methods={"POST"})
     */
    public function delete(Request $request, Projet $projet, ProjetRepository $projetRepository): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        if ($this->isCsrfTokenValid('delete'.$projet->getId(), $request->request->get('_token'))) {
            $projetRepository->remove($projet, true);
        }

        return $this->redirectToRoute('app_projet_index', [], Response::HTTP_SEE_OTHER);
    }

    
    /**
     * @IsGranted("ROLE_OWNER")
     * @Route("/{id}/launch", name="app_projet_launch")
     */
    public function launchProjet($id , EntityManagerInterface $em)
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        $repo = $em->getRepository(Projet::class);
        // retrive the task
        $projet = $repo->findOneById($id);
      
        

        if($projet->getEtat() == 'Open'){
            $projet->setEtat('In Progress');
            $projet->setDateDebut(new \DateTime());
            $em->persist($projet);
            $em->flush();
        }
        else {
            return $this->redirectToRoute('app_projet_index');
        }
       

        return $this->redirectToRoute('app_projet_show' , ['id' => $id]);
    }

    /**
     * @IsGranted("ROLE_OWNER")
     * @Route("/{id}/finish", name="app_projet_finish")
     */
    public function finishProjet($id , EntityManagerInterface $em)
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        $repo = $em->getRepository(Projet::class);
        // retrive the task
        $projet = $repo->findOneById($id);
      
        

        if($projet->getEtat() == 'In Progress'){
            $projet->setEtat('Finished');
            $projet->setDateFin(new \DateTime());
            $em->persist($projet);
            $em->flush();
        }
        else {
            return $this->redirectToRoute('app_projet_index');
        }
       

        return $this->redirectToRoute('app_projet_show' , ['id' => $id]);
    }


    /**
     * @IsGranted("ROLE_OWNER")
     * @Route("/{id}/cancel", name="app_projet_cancel")
     */
    public function cancelProjet($id , EntityManagerInterface $em)
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        $repo = $em->getRepository(Projet::class);
        // retrive the task
        $projet = $repo->findOneById($id);
      
        if($projet->getEtat() != 'Finished'){
            $projet->setEtat('Cancelled');
            $projet->setDateFin(new \DateTime());
            $em->persist($projet);
            $em->flush();
        }
        else {
            return $this->redirectToRoute('app_projet_index');
        }
       

        return $this->redirectToRoute('app_projet_show' , ['id' => $id]);
    }
}

templates/projet/_delete_form.html.twig
<form method="post" action="{{ path('app_projet_delete', {'id': projet.id}) }}" style='display:inline;' onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ projet.id) }}">
    <button class="btn btn-danger btn-sm">  <i class="fa fa-trash"></i></button>
</form>

templates/projet/_form.html.twig
{{ form_start(form) }}
    <div class="row text-center">
        <div class="col-6">
            <div class="row "> 
                    <div class="col align self-center"> 
                        <label>Client:</label>
                        {{ form_row(form.client , {'label': ' '}) }}
                    </div>
            </div>
            <div class="row "> 
                <div class="col align self-center"> 
                    <label >Intitule:</label><br>
                    {{ form_row(form.intitule, {'label': ' ', 'attr':
                    {'placeholder':'Intitule...'}})  }}
                </div>
            </div>
            
            <div class="row "> 
                <div class="col align self-center"> 
                    <label >Categorie:</label><br>
                    {{ form_row(form.Categorie, {'label': ' ', 'attr':
                    {'placeholder':'catégorie...'}})  }}
                </div>
            </div>
            
        </div>
        <div class="col-6">
            <div class="row "> 
                <div class="col mt-5 align self-center"> 
                    <label >Budget:</label><br>
                    {{ form_row(form.budget, {'label': ' ', 'attr':
                    {'placeholder':'Budget...'}})  }}
                </div>
            </div>
            <div class="row "> 
                <div class="col align self-center"> 
                    <label >Description:</label><br>
                    {{ form_row(form.description, {'label': ' ', 'attr':
                    {'placeholder':'description...'}})  }}
                   
                </div>
            </div>
            <div class="row "> 
                <div class="col align self-center mt-3"> 
                   <button class="btn btn-primary btn-sm">{{ button_label|default('Save') }}</button>
                    <a class="mt-5" href="{{ path('app_projet_index') }}">Return</a>
                </div>
            </div>
            
        </div>
</div>
    
{{ form_end(form) }}

templates/projet/associerEmployee.html.twig
{% extends 'base.html.twig' %}

{% block title %}Associer Employe{% endblock %}

{% block body %}
<div class="container mt-5">
    <div class="row">
    <div class="col mt-5">
        <h1>Associer Employe</h1>
        {{ form_start(AssocEmployeForm)}}
            <div class="row">
                </div class="col-6 text-center">
                <label>Employee:</label>
                {{form_row(AssocEmployeForm.Employe , {'label': ' '})}}</br>
                <label>Role:</label>
                {{form_row(AssocEmployeForm.role , {'label': ' '})}}</br>
                </div>
            </div>
            
            <button type="submit" class="btn btn-primary btn-sm">Associer </button>
            <a class="mt-5" href="{{ path('app_projet_show', {'id': projet.id}) }}">Return</a>

        {{ form_end(AssocEmployeForm)}}
    </div>
    </div>
</div>

{% endblock %}

templates/projet/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Projet{% endblock %}

{% block body %}
    <div class="container mt-5"> 
    <div class="row">
        <div class="col-6 mt-5">
            <h1 class="text-center">Update Projet</h1>
        </div>
    </div>
    <div class="row "> 
        <div class="col"> 
            {{ include('projet/_form.html.twig', {'button_label': 'Update'}) }}
        </div>
    </div>     
</div>
{% endblock %}

templates/projet/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Projets{% endblock %}

{% block body %}

<div class="container mt-5">
        <div class="row text-right">
            <div class="col-11 mt-5">
            <h1>Projets</h1>
            </div>
            <div class="col-1 float-right mt-5">
                {% if is_granted("ROLE_OWNER") %}
                    <a  href="{{ path('app_projet_new')}}"><button type="button"  
                        class="btn btn-primary btn-sm">
                            Add</button> </a>
                {% endif %}
            </div>
        </div>
        <div class="row mt-3">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th scope="col" class="text-center">Intitule</th>
                            <th scope="col" class="text-center">Etat</th>
                            <th scope="col" class="text-center">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for projet in projets %}
                        {% set url= path ('app_projet_show', {id: projet.id}) %}
                            <tr class="table-primary">
                                <th scope="row" class="text-center"> <a href="{{ url }}">{{projet.intitule}}</a></th>
                                <td class="text-center">{{ projet.etat }}</td>
                                <td class="text-center"> 
                                    <a class="btn btn-primary btn-sm" 
                                    href="{{ path('app_projet_show',{"id": projet.id}) }}" role="button">
                                    <i class="fa fa-info"></i></a>
                                    {% if is_granted("ROLE_OWNER") %}
                                        <a class="btn btn-success btn-sm" 
                                        href="{{ path('app_projet_edit',{"id": projet.id}) }}" role="button">
                                        <i class="fa fa-edit"></i></a>
                                        {{ include('projet/_delete_form.html.twig') }}
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table> 
        </div>
    </div>  
    
    
{% endblock %}

templates/projet/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Projet{% endblock %}

{% block body %}
<div class="container mt-5"> 
    <div class="row">
        <div class="col-6 mt-5">
            <h1 class="text-center">Create Projet</h1>
        </div>
    </div>
    <div class="row "> 
        <div class="col"> 
            {{ include('projet/_form.html.twig') }}
        </div>
    </div>     
</div>
    
{% endblock %}

templates/projet/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{projet.intitule}}{% endblock %}

{% block body %}

    <div class="container mt-5">
        <div class="row">
            <div class="col-6 mt-2">
                <h2 class="display-4 mt-5"> {{ projet.intitule | upper}} </h2>
                <small></small>
                <hr>
            </div>
        </div>
        <div class="row border rounded">
            <div class="col-6 text-center">
                <h6>Categorie: {{ projet.Categorie }}<h6>
                <h6>Budget: {{ projet.budget }}<h6>
                <h6>Etat: {{ projet.etat }}<h6>
            </div>
            <div class="col-6  text-center">
                <h6>Date Debut: {{ projet.dateDebut is empty ? "" : projet.dateDebut|date("d/m/Y") }}<h6>
                <h6>Date Fin: {{ projet.dateFin is empty ? "" : projet.dateFin|date("d/m/Y") }}<h6> 
                <h6>Client: {{ projet.client.ClientNom }} {{ projet.client.ClientPrenom }}<h6> 
                <h6>Description: {{ projet.description }}<h6> 
            </div>
        </div>
        <div class="row">
            <div class="col-10 mt-3">
                <a href="{{ path('app_projet_index') }}">
                <button type="button" class="btn btn-primary btn-sm">Return</button></a>
    
                {% if is_granted("ROLE_OWNER") and projet.etat == "Open" %}
                    <a href="{{ path('app_projet_launch' , {'id': projet.id}) }}">
                    <button type="button" class="btn btn-success btn-sm">Launch</button></a>
                {% endif %}

                {% if is_granted("ROLE_OWNER") and projet.etat == "In Progress" %}
                    <a href="{{ path('app_projet_finish' , {'id': projet.id}) }}">
                    <button type="button" class="btn btn-success btn-sm">Cloturer</button></a>
                {% endif %}
                {% if is_granted("ROLE_OWNER") and projet.etat != "Finished" and projet.etat != "Cancelled" %}
                    <a href="{{ path('app_projet_cancel' , {'id': projet.id}) }}">
                    <button type="button" class="btn btn-danger btn-sm">Cancel</button></a>
                {% endif %}

            </div>
            <div class="col-2 mt-3">
            {% if is_granted("ROLE_OWNER") %}
                <a href="{{ path('app_projet_edit', {'id': projet.id}) }}">
                <button type="button"  class="btn btn-success btn-sm"> <i class="fa fa-edit"></i></button></a>

                    {{ include('projet/_delete_form.html.twig') }} 
            {% endif %}
            </div>
        </div>
        <hr class=" mx-auto w-25 p-1" style="background-color: #ADB5BD;" >
        {% if is_granted("ROLE_OWNER")  or is_granted("ROLE_MANAGER") %}
                <h2>Employees</h2>
                <div class="row mb-3">
                {% if is_granted("ROLE_OWNER") and projet.etat == "In Progress" %}
                    <a href="{{ path('app_user_projet_assoc' , {"id": projet.id}) }}"><button type="button"  
                            class="btn btn-primary btn-sm">
                                Add Employe</button> </a>
                {% endif %}
                </div>
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th scope="col">Photo</th>
                            <th scope="col">Employe</th>
                            <th scope="col">FullName</th>
                            <th scope="col">Role</th>
                            <th scope="col">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for employee in employees %}
                            
                            <tr class="table-primary">
                                {% if employee.user.image == null %}
                                    {% if employee.user.sexe == 'M' %}
                                        <th style="vertical-align:middle;" scope="row">
                                        <img src="{{ asset('/ProfileImg/M.jpeg') }}" width="75"
                                            height="75" class=" float-left mr-3 img-fluid my-2 rounded-circle" ></th>
                                    {% else %}
                                        <th style="vertical-align:middle;" scope="row">
                                        <img src="{{ asset('/ProfileImg/F.png') }}" width="75"
                                            height="75" class=" float-left mr-3 img-fluid my-2 rounded-circle"></th>
                                    {% endif %}

                                {% else %}
                                    <th scope="row">
                                        <img src="{{ asset('/ProfileImg/'~employee.user.image) }}" width="75"
                                            height="75" class="img-fluid my-2 rounded-circle" ></th>
                                {% endif %}
                                
                                <td style="vertical-align:middle;">{{employee.user.username}}</a></td>
                                <td style="vertical-align:middle;">{{employee.user.LastName}} {{employee.user.FirstName}}</td>
                                <td style="vertical-align:middle;">{{employee.RoleInProjet}}</td>
                                <td style="vertical-align:middle;"> 
                                    <a class="btn btn-primary btn-sm" 
                                    href="{{ path('security_users_show' , {"id": employee.user.id})  }}" role="button">
                                    <i class="fa fa-info"></i>
                                    </a>
                                    {% if is_granted("ROLE_OWNER")  and projet.etat == "In Progress" %}
                                    <a class="btn btn-danger btn-sm" 
                                    href="{{ path('app_user_projet_retirer' , {"id": employee.id})  }}" role="button">
                                    <i class="fa fa-remove"></i></a>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
        {% endif %}


        <h2>Phases</h2>
        <div class="row mb-3">
                {% if is_granted("ROLE_MANAGER") and projet.etat == "In Progress" %}
                    <a href="{{ path('app_phase_new') }}"><button type="button"  
                            class="btn btn-primary btn-sm">
                                Add Phase</button> </a>
                {% endif %}
        </div>

        <table class="table table-hover">
            <thead>
            <tr>
                <th scope="col">Intitule</th>
                <th scope="col">Statut</th>
                <th scope="col">Actions</th>

            </tr>
            </thead>
            <tbody>
            {% for phase in phases %}
                <tr class="table-primary">

                    <td>{{phase.intitule}}</td>
                    <td>{{phase.status}}</td>

                    <td>
                        <a class="btn btn-primary btn-sm"
                           href="{{ path('app_phase_show' , {"id": phase.id})  }}" role="button">
                            <i class="fa fa-info"></i></a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}